@startuml
hide empty members
skinparam classAttributeIconSize 0

interface ICS_UI
interface ICS_DAG
interface ICS_FE_Non
interface ICS_FE_Importable
interface ICS_FE_Exportable
interface ICS_FE_Importable_Exportable
interface ICS_DB
interface ICS_Data
interface ICS_Executable
interface ICS_Reportable
interface ICS_Load

interface "ICS_Base_0<CS_FE_Non_t>"
interface "ICS_Base_0<CS_FE_Importable_t>"
interface "ICS_Base_0<CS_FE_Exportable_t>"
interface "ICS_Base_0<CS_FE_Importable_Exportable_t>"
interface ICS_Base_1

interface "ICS_Base<CS_FE_Non_t, CS_Non_Updatable_t>"
interface "ICS_Base<CS_FE_Non_t, CS_Ancestor_Updatable_t>"
interface "ICS_Base<CS_FE_Non_t, CS_Invariant_Updatable_t>"
interface "ICS_Base<CS_FE_Importable_t, CS_Non_Updatable_t>"
interface "ICS_Base<CS_FE_Importable_t, CS_Ancestor_Updatable_t>"
interface "ICS_Base<CS_FE_Importable_t, CS_Invariant_Updatable_t>"
interface "ICS_Base<CS_FE_Exportable_t, CS_Non_Updatable_t>"
interface "ICS_Base<CS_FE_Exportable_t, CS_Ancestor_Updatable_t>"
interface "ICS_Base<CS_FE_Exportable_t, CS_Invariant_Updatable_t>"
interface "ICS_Base<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t>"
interface "ICS_Base<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t>"
interface "ICS_Base<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t>"

interface "ICS_EO<CS_FE_Non_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Non_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Non_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_EO<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"

interface "ICS_SC<CS_FE_Non_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Non_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Non_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
interface "ICS_SC<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"

ICS_FE_Non <|-- "ICS_Base_0<CS_FE_Non_t>"
ICS_FE_Importable <|-- "ICS_Base_0<CS_FE_Importable_t>"
ICS_FE_Exportable <|-- "ICS_Base_0<CS_FE_Exportable_t>"
ICS_FE_Importable_Exportable <|-- "ICS_Base_0<CS_FE_Importable_Exportable_t>"

ICS_UI <|-- ICS_Base_1
ICS_DAG <|-- ICS_Base_1
ICS_DB <|-- ICS_Base_1
ICS_Data <|-- ICS_Base_1

"ICS_Base_0<CS_FE_Non_t>" <|-- "ICS_Base<CS_FE_Non_t, CS_Non_Updatable_t>"
"ICS_Base_0<CS_FE_Non_t>" <|-- "ICS_Base<CS_FE_Non_t, CS_Ancestor_Updatable_t>"
"ICS_Base_0<CS_FE_Non_t>" <|-- "ICS_Base<CS_FE_Non_t, CS_Invariant_Updatable_t>"
"ICS_Base_0<CS_FE_Importable_t>" <|-- "ICS_Base<CS_FE_Importable_t, CS_Non_Updatable_t>"
"ICS_Base_0<CS_FE_Importable_t>" <|-- "ICS_Base<CS_FE_Importable_t, CS_Ancestor_Updatable_t>"
"ICS_Base_0<CS_FE_Importable_t>" <|-- "ICS_Base<CS_FE_Importable_t, CS_Invariant_Updatable_t>"
"ICS_Base_0<CS_FE_Exportable_t>" <|-- "ICS_Base<CS_FE_Exportable_t, CS_Non_Updatable_t>"
"ICS_Base_0<CS_FE_Exportable_t>" <|-- "ICS_Base<CS_FE_Exportable_t, CS_Ancestor_Updatable_t>"
"ICS_Base_0<CS_FE_Exportable_t>" <|-- "ICS_Base<CS_FE_Exportable_t, CS_Invariant_Updatable_t>"
"ICS_Base_0<CS_FE_Importable_Exportable_t>" <|-- "ICS_Base<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t>"
"ICS_Base_0<CS_FE_Importable_Exportable_t>" <|-- "ICS_Base<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t>"
"ICS_Base_0<CS_FE_Importable_Exportable_t>" <|-- "ICS_Base<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t>"

ICS_Base_1 <|-- "ICS_Base<CS_FE_Non_t, CS_Non_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Non_t, CS_Ancestor_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Non_t, CS_Invariant_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Importable_t, CS_Non_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Importable_t, CS_Ancestor_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Importable_t, CS_Invariant_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Exportable_t, CS_Non_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Exportable_t, CS_Ancestor_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Exportable_t, CS_Invariant_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t>"
ICS_Base_1 <|-- "ICS_Base<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t>"

"ICS_Base<CS_FE_Non_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Non_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Non_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Non_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Non_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t>" <|-- "ICS_EO<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"

"ICS_Base<CS_FE_Non_t, CS_Non_Updatable_t>" <|-- "ICS_SC<CS_FE_Non_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Non_Updatable_t>" <|-- "ICS_SC<CS_FE_Non_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Ancestor_Updatable_t>" <|-- "ICS_SC<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Ancestor_Updatable_t>" <|-- "ICS_SC<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Invariant_Updatable_t>" <|-- "ICS_SC<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Non_t, CS_Invariant_Updatable_t>" <|-- "ICS_SC<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Non_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Non_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Invariant_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_t, CS_Invariant_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Non_Updatable_t>" <|-- "ICS_SC<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Non_Updatable_t>" <|-- "ICS_SC<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_SC<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_SC<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Invariant_Updatable_t>" <|-- "ICS_SC<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Exportable_t, CS_Invariant_Updatable_t>" <|-- "ICS_SC<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
"ICS_Base<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t>" <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"

ICS_Executable <|-- ICS_SC_0
ICS_Reportable <|-- ICS_SC_0
ICS_Load <|-- ICS_SC_0

ICS_SC_0 <|-- "ICS_SC<CS_FE_Non_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Non_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Non_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Non_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Exportable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Exportable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Ancestor_Updatable_t, CS_Manual_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>"
ICS_SC_0 <|-- "ICS_SC<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>"

class CS_EO_Mat1 {
    +std::string _DB_descriptor
}

class CS_EO_Panel {
    +double _thickness
    +double _width_a
    +double _width_b
    +CS_DT_DN<CS_EO_Mat1>" _EO_mat1
}

class CS_SC_Panel {
    +CS_DT_DN<CS_EO_Panel>" _EO_panel
    +CS_DT_DN<EO_Stiffener>" _EO_side_stiffener_1
    +CS_DT_DN<EO_Stiffener>" _EO_side_stiffener_2
    +CS_DT_DN<EO_SCL_Panel>" _EO_SCL_panel
}

"ICS_EO<CS_FE_Importable_Exportable_t, CS_Non_Updatable_t, CS_Non_Sizeable_t>" <|-- CS_EO_Mat1
"ICS_EO<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Auto_Sizeable_t>" <|-- CS_EO_Panel
"ICS_SC<CS_FE_Importable_Exportable_t, CS_Invariant_Updatable_t, CS_Manual_Sizeable_t>" <|-- CS_SC_Panel

@enduml
