@startuml
skinparam classAttributeIconSize 0

class FE_Non_t
class FE_Importable_t
class FE_Exportable_t
class FE_Importable_Exportable_t
class Non_Updatable_t
class Ancestor_Updatable_t
class Invariant_Updatable_t
class Non_Sizeable_t
class Auto_Sizeable_t
class Manual_Sizeable_t

interface IUI
interface IDAG
interface IFE_Non
interface IFE_Importable
interface IFE_Exportable
interface IFE_Importable_Exportable
interface IDB
interface ICS_Data
interface IExecutable
interface IReportable
interface ILoad
interface ISC_0
interface ICS_0<FEType>
interface ICS<FEType, UpdateableType>
interface IEO<FEType, UpdateableType, SizeableType>
interface ISC<FEType, UpdateableType, SizeableType>

IFE_Non <|-- ICS_0<FE_Non_t>
IFE_Importable <|-- ICS_0<FE_Importable_t>
IFE_Exportable <|-- ICS_0<FE_Exportable_t>
IFE_Importable_Exportable <|-- ICS_0<FE_Importable_Exportable_t>

ICS_0<FE_Non_t> <|-- ICS<FE_Non_t, Non_Updatable_t>
ICS_0<FE_Non_t> <|-- ICS<FE_Non_t, Ancestor_Updatable_t>
ICS_0<FE_Non_t> <|-- ICS<FE_Non_t, Invariant_Updatable_t>
ICS_0<FE_Importable_t> <|-- ICS<FE_Importable_t, Non_Updatable_t>
ICS_0<FE_Importable_t> <|-- ICS<FE_Importable_t, Ancestor_Updatable_t>
ICS_0<FE_Importable_t> <|-- ICS<FE_Importable_t, Invariant_Updatable_t>
ICS_0<FE_Exportable_t> <|-- ICS<FE_Exportable_t, Non_Updatable_t>
ICS_0<FE_Exportable_t> <|-- ICS<FE_Exportable_t, Ancestor_Updatable_t>
ICS_0<FE_Exportable_t> <|-- ICS<FE_Exportable_t, Invariant_Updatable_t>
ICS_0<FE_Importable_Exportable_t> <|-- ICS<FE_Importable_Exportable_t, Non_Updatable_t>
ICS_0<FE_Importable_Exportable_t> <|-- ICS<FE_Importable_Exportable_t, Ancestor_Updatable_t>
ICS_0<FE_Importable_Exportable_t> <|-- ICS<FE_Importable_Exportable_t, Invariant_Updatable_t>

ICS<FE_Non_t, Non_Updatable_t> <|-- IEO<FE_Non_t, Non_Updatable_t, Non_Sizeable_t>
ICS<FE_Non_t, Non_Updatable_t> <|-- IEO<FE_Non_t, Non_Updatable_t, Auto_Sizeable_t>
ICS<FE_Non_t, Non_Updatable_t> <|-- IEO<FE_Non_t, Non_Updatable_t, Manual_Sizeable_t>
ICS<FE_Non_t, Ancestor_Updatable_t> <|-- IEO<FE_Non_t, Ancestor_Updatable_t, Non_Sizeable_t>
ICS<FE_Non_t, Ancestor_Updatable_t> <|-- IEO<FE_Non_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ICS<FE_Non_t, Ancestor_Updatable_t> <|-- IEO<FE_Non_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ICS<FE_Non_t, Invariant_Updatable_t> <|-- IEO<FE_Non_t, Invariant_Updatable_t, Non_Sizeable_t>
ICS<FE_Non_t, Invariant_Updatable_t> <|-- IEO<FE_Non_t, Invariant_Updatable_t, Auto_Sizeable_t>
ICS<FE_Non_t, Invariant_Updatable_t> <|-- IEO<FE_Non_t, Invariant_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_t, Non_Updatable_t> <|-- IEO<FE_Importable_t, Non_Updatable_t, Non_Sizeable_t>
ICS<FE_Importable_t, Non_Updatable_t> <|-- IEO<FE_Importable_t, Non_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_t, Non_Updatable_t> <|-- IEO<FE_Importable_t, Non_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_t, Ancestor_Updatable_t> <|-- IEO<FE_Importable_t, Ancestor_Updatable_t, Non_Sizeable_t>
ICS<FE_Importable_t, Ancestor_Updatable_t> <|-- IEO<FE_Importable_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_t, Ancestor_Updatable_t> <|-- IEO<FE_Importable_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_t, Invariant_Updatable_t> <|-- IEO<FE_Importable_t, Invariant_Updatable_t, Non_Sizeable_t>
ICS<FE_Importable_t, Invariant_Updatable_t> <|-- IEO<FE_Importable_t, Invariant_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_t, Invariant_Updatable_t> <|-- IEO<FE_Importable_t, Invariant_Updatable_t, Manual_Sizeable_t>
ICS<FE_Exportable_t, Non_Updatable_t> <|-- IEO<FE_Exportable_t, Non_Updatable_t, Non_Sizeable_t>
ICS<FE_Exportable_t, Non_Updatable_t> <|-- IEO<FE_Exportable_t, Non_Updatable_t, Auto_Sizeable_t>
ICS<FE_Exportable_t, Non_Updatable_t> <|-- IEO<FE_Exportable_t, Non_Updatable_t, Manual_Sizeable_t>
ICS<FE_Exportable_t, Ancestor_Updatable_t> <|-- IEO<FE_Exportable_t, Ancestor_Updatable_t, Non_Sizeable_t>
ICS<FE_Exportable_t, Ancestor_Updatable_t> <|-- IEO<FE_Exportable_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ICS<FE_Exportable_t, Ancestor_Updatable_t> <|-- IEO<FE_Exportable_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ICS<FE_Exportable_t, Invariant_Updatable_t> <|-- IEO<FE_Exportable_t, Invariant_Updatable_t, Non_Sizeable_t>
ICS<FE_Exportable_t, Invariant_Updatable_t> <|-- IEO<FE_Exportable_t, Invariant_Updatable_t, Auto_Sizeable_t>
ICS<FE_Exportable_t, Invariant_Updatable_t> <|-- IEO<FE_Exportable_t, Invariant_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_Exportable_t, Non_Updatable_t> <|-- IEO<FE_Importable_Exportable_t, Non_Updatable_t, Non_Sizeable_t>
ICS<FE_Importable_Exportable_t, Non_Updatable_t> <|-- IEO<FE_Importable_Exportable_t, Non_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_Exportable_t, Non_Updatable_t> <|-- IEO<FE_Importable_Exportable_t, Non_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_Exportable_t, Ancestor_Updatable_t> <|-- IEO<FE_Importable_Exportable_t, Ancestor_Updatable_t, Non_Sizeable_t>
ICS<FE_Importable_Exportable_t, Ancestor_Updatable_t> <|-- IEO<FE_Importable_Exportable_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_Exportable_t, Ancestor_Updatable_t> <|-- IEO<FE_Importable_Exportable_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_Exportable_t, Invariant_Updatable_t> <|-- IEO<FE_Importable_Exportable_t, Invariant_Updatable_t, Non_Sizeable_t>
ICS<FE_Importable_Exportable_t, Invariant_Updatable_t> <|-- IEO<FE_Importable_Exportable_t, Invariant_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_Exportable_t, Invariant_Updatable_t> <|-- IEO<FE_Importable_Exportable_t, Invariant_Updatable_t, Manual_Sizeable_t>

ICS<FE_Non_t, Non_Updatable_t> <|-- ISC<FE_Non_t, Non_Updatable_t, Auto_Sizeable_t>
ICS<FE_Non_t, Non_Updatable_t> <|-- ISC<FE_Non_t, Non_Updatable_t, Manual_Sizeable_t>
ICS<FE_Non_t, Ancestor_Updatable_t> <|-- ISC<FE_Non_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ICS<FE_Non_t, Ancestor_Updatable_t> <|-- ISC<FE_Non_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ICS<FE_Non_t, Invariant_Updatable_t> <|-- ISC<FE_Non_t, Invariant_Updatable_t, Auto_Sizeable_t>
ICS<FE_Non_t, Invariant_Updatable_t> <|-- ISC<FE_Non_t, Invariant_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_t, Non_Updatable_t> <|-- ISC<FE_Importable_t, Non_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_t, Non_Updatable_t> <|-- ISC<FE_Importable_t, Non_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_t, Ancestor_Updatable_t> <|-- ISC<FE_Importable_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_t, Ancestor_Updatable_t> <|-- ISC<FE_Importable_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_t, Invariant_Updatable_t> <|-- ISC<FE_Importable_t, Invariant_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_t, Invariant_Updatable_t> <|-- ISC<FE_Importable_t, Invariant_Updatable_t, Manual_Sizeable_t>
ICS<FE_Exportable_t, Non_Updatable_t> <|-- ISC<FE_Exportable_t, Non_Updatable_t, Auto_Sizeable_t>
ICS<FE_Exportable_t, Non_Updatable_t> <|-- ISC<FE_Exportable_t, Non_Updatable_t, Manual_Sizeable_t>
ICS<FE_Exportable_t, Ancestor_Updatable_t> <|-- ISC<FE_Exportable_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ICS<FE_Exportable_t, Ancestor_Updatable_t> <|-- ISC<FE_Exportable_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ICS<FE_Exportable_t, Invariant_Updatable_t> <|-- ISC<FE_Exportable_t, Invariant_Updatable_t, Auto_Sizeable_t>
ICS<FE_Exportable_t, Invariant_Updatable_t> <|-- ISC<FE_Exportable_t, Invariant_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_Exportable_t, Non_Updatable_t> <|-- ISC<FE_Importable_Exportable_t, Non_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_Exportable_t, Non_Updatable_t> <|-- ISC<FE_Importable_Exportable_t, Non_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_Exportable_t, Ancestor_Updatable_t> <|-- ISC<FE_Importable_Exportable_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_Exportable_t, Ancestor_Updatable_t> <|-- ISC<FE_Importable_Exportable_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ICS<FE_Importable_Exportable_t, Invariant_Updatable_t> <|-- ISC<FE_Importable_Exportable_t, Invariant_Updatable_t, Auto_Sizeable_t>
ICS<FE_Importable_Exportable_t, Invariant_Updatable_t> <|-- ISC<FE_Importable_Exportable_t, Invariant_Updatable_t, Manual_Sizeable_t>

IExecutable <|-- ISC_0
IReportable <|-- ISC_0
ILoad <|-- ISC_0

ISC_0 <|-- ISC<FE_Non_t, Non_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Non_t, Non_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Non_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Non_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Non_t, Invariant_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Non_t, Invariant_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_t, Non_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_t, Non_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_t, Invariant_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_t, Invariant_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Exportable_t, Non_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Exportable_t, Non_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Exportable_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Exportable_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Exportable_t, Invariant_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Exportable_t, Invariant_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_Exportable_t, Non_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_Exportable_t, Non_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_Exportable_t, Ancestor_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_Exportable_t, Ancestor_Updatable_t, Manual_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_Exportable_t, Invariant_Updatable_t, Auto_Sizeable_t>
ISC_0 <|-- ISC<FE_Importable_Exportable_t, Invariant_Updatable_t, Manual_Sizeable_t>

class EO_Mat1 {
    +std::string _DB_descriptor
}

class EO_Panel {
    +double _thickness
    +double _width_a
    +double _width_b
    +CS_DT_DN<EO_Mat1> _EO_mat1
}

class SC_Panel {
    +CS_DT_DN<EO_Panel> _EO_panel
    +CS_DT_DN<EO_Stiffener> _EO_side_stiffener_1
    +CS_DT_DN<EO_Stiffener> _EO_side_stiffener_2
    +CS_DT_DN<EO_SCL_Panel> _EO_SCL_panel
}

IEO<FE_Importable_Exportable_t, Non_Updatable_t, Non_Sizeable_t> <|-- EO_Mat1
IEO<FE_Importable_Exportable_t, Invariant_Updatable_t, Auto_Sizeable_t> <|-- EO_Panel
IEO<FE_Importable_Exportable_t, Invariant_Updatable_t, Manual_Sizeable_t> <|-- SC_Panel

@enduml
