@startuml UC_01

start
:[SAE] Select FE;
:[UI] Call [System] for import;
:[System] Create DAG for FE;

if (Import error?) then (no)
  :[System] Call [UI] to initialize;
  :[UI] Initialize;
  :[SAE] Select SA dataset;
  :[SAE] Click "Run SAMM";
  :[UI] Call [System] for SAMM run;
  :[System] Get dataset from DAG;

  if (Dataset error?) then (no)
    :[System] Execute SAMM;

    if (Computation error?) then (no)
      :[System] Create DAG nodes for "Results";
      :[System] Call [UI] to update the states and results;
      :[UI] Update states in SCT and RFs in the current form;
    else (yes)
      :[System] log;
      :[System] Set status to Error;
      :[System] Wait end of SAMM run;
      :[System] Call [UI] for update and message;
      :[UI] Update for non-failed SAMMs;
      :[UI] Show message for failed SAMMs;
      stop;
    endif
  else (yes)
    :[System] Terminate SAMM run;
    :[System] Call [UI] for meassage;
    :[UI] Show message;
    stop;
  endif
else (yes)
  :[System] Terminate FE import;
  :[System] log;
  :[System] Call [UI] for message;
  :[UI] Show message;
  stop;
endif

stop;

@enduml
