@startuml use_case_diagram_2

start
:[Ordinary User] Select a sub-DCG;
:[UI] Call [System] for sub-DCG load;
:[System] Load sub-DCG;
:[System] Initialize UI;
:[UI] Initialize the forms and FE graphics;

repeat
  :[Ordinary User] Review SARs for failed SCs;
  :[Ordinary User] Update failed SCs;
  :[UI] Call [System] to set updates to DB;
  :[System] Update DB;
  :[System] Set OutOfDate for SARs of updated SCs;
  :[Ordinary User] Run SAMMs;
  :[UI] Call [System] to run SAMMs;
  :[System] Run SAMMs;
  :[System] Update SARs and set their state as UpToDate;
  :[System] Call [UI] to present updated SARs;
  :[Ordinary User] Review SARs for failed SCs;
repeat while (Failed SCs exists?)

:[Ordinary User] Select save the sub-DCG;
:[UI] Call [System] to save the sub-DCG;
:[System] Save the sub-DCG;

@enduml
