1. **Ordinary User** selects to create a SC and auxilary items required by the SC and SAMM (e.g. material and load).
2. **UI** emits an event to activate the system to create the requested objects.
3. **System** creates the requested objects.
4. **System** emits an event to initialize the user forms.
5. **UI** initializes the user forms.
6. **Ordinary User** fills the fields of the objects.
7. **Ordinary User** selects to run the requested SAMMs.
8. **UI** emits an event to activate the system to run the requested SAMMs.
9. **System** runs the requested SAMMs.
10. **System** updates the SARs.
11. **System** emits an event to activate the UI for the SARs.
12. **UI** refreshes the SARs for the values.
13. **Ordinary User** reviews the SARs.

@startuml use_case_diagram_3

start
:[Ordinary User] Create SC and auxillary;
:[UI] Call [System] for object construction;
:[System] Create the objects;
:[System] Initialize UI;
:[UI] Initialize the forms;
:[Ordinary User] Enter inputs;
:[Ordinary User] Select and run SAMM;
:[UI] Call [System] to run SAMM;
:[System] Run SAMM;
:[System] Update SAR;
:[System] Call [UI] for SAR;
:[UI] Refresh form of SAR;
:[Ordinary User] Review SAR;

@enduml
