CREATE TABLE mat8 (
    mat8_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(99) NOT NULL UNIQUE,
    E11  FLOAT NOT NULL,
    E22  FLOAT NOT NULL,
    G12  FLOAT NOT NULL,
    nu12 FLOAT NOT NULL
);
