# .github/workflows/plantuml.yml
name: Render PlantUML Diagrams

# Trigger on pushes that include any .puml under uml/
on:
  push:
    paths:
      - 'uml/**/*.puml'

jobs:
  render-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java (required by PlantUML)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Render all PlantUML files to SVG
        uses: clarzu/plantuml-action@v2
        with:
          # Glob for all .puml files under uml/
          path: 'uml/**/*.puml'
          format: svg

      - name: Commit generated diagrams
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add uml/**/*.svg
          git diff --quiet || git commit -m "Auto-render PlantUML diagrams"
          git push
